apiVersion: galasa.dev/v2alpha1
kind: GalasaEcosystem
metadata:
  name: test
  namespace: jdavies47
spec:
  hostname: "http://cicsk8sm.hursley.ibm.com"
  galasaVersion: "main"
  busyboxImage: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/library/busybox:latest
  componentsSpec:
    cps: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        platform: hdc
    ras: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        platform: hdc
    api: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        platform: hdc
    enginecontroller: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64
    resmon: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64
    metrics: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64